[package]
name = "mc"
version = "0.1.0"
authors = ["Daniel Conley <danielc030417@gmail.com>"]
edition = "2018"

[dependencies]
bit_range = "0.1.0"
enum_dispatch = "0.3.4"
libloading = "0.6.5"
serde = "1.0.117"
serde_json = "1.0.59"
hematite-nbt = "0.5.0"
