[package]
name = "java-intake"
version = "0.1.0"
authors = ["Daniel Conley <danielc030417@gmail.com>"]
edition = "2018"

[dependencies]
hermaphrodite = {path = "../hermaphrodite"}
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.59"
