[package]
name = "compile-in"
version = "0.1.0"
authors = ["Daniel Conley <danielc030417@gmail.com>"]
edition = "2018"

[dependencies]
hermaphrodite = {path = "../hermaphrodite"}
java-intake = {path = "../java-intake"}
serde = "*"
